// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netty_io_proto.proto

package com.zqgame.netty.io.proto;

public final class NettyIoProto {
  private NettyIoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zqgame.netty.io.proto.NettyIoProto.Head)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *协议名
     * </pre>
     *
     * <code>string proto = 1;</code>
     */
    java.lang.String getProto();
    /**
     * <pre>
     *协议名
     * </pre>
     *
     * <code>string proto = 1;</code>
     */
    com.google.protobuf.ByteString
        getProtoBytes();

    /**
     * <pre>
     *执行的方法
     * </pre>
     *
     * <code>string toMethod = 2;</code>
     */
    java.lang.String getToMethod();
    /**
     * <pre>
     *执行的方法
     * </pre>
     *
     * <code>string toMethod = 2;</code>
     */
    com.google.protobuf.ByteString
        getToMethodBytes();
  }
  /**
   * <pre>
   *报文头部
   * </pre>
   *
   * Protobuf type {@code com.zqgame.netty.io.proto.NettyIoProto.Head}
   */
  public  static final class Head extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zqgame.netty.io.proto.NettyIoProto.Head)
      HeadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Head.newBuilder() to construct.
    private Head(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Head() {
      proto_ = "";
      toMethod_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Head(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              proto_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              toMethod_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Head_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Head_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zqgame.netty.io.proto.NettyIoProto.Head.class, com.zqgame.netty.io.proto.NettyIoProto.Head.Builder.class);
    }

    public static final int PROTO_FIELD_NUMBER = 1;
    private volatile java.lang.Object proto_;
    /**
     * <pre>
     *协议名
     * </pre>
     *
     * <code>string proto = 1;</code>
     */
    public java.lang.String getProto() {
      java.lang.Object ref = proto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proto_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *协议名
     * </pre>
     *
     * <code>string proto = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProtoBytes() {
      java.lang.Object ref = proto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOMETHOD_FIELD_NUMBER = 2;
    private volatile java.lang.Object toMethod_;
    /**
     * <pre>
     *执行的方法
     * </pre>
     *
     * <code>string toMethod = 2;</code>
     */
    public java.lang.String getToMethod() {
      java.lang.Object ref = toMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toMethod_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *执行的方法
     * </pre>
     *
     * <code>string toMethod = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToMethodBytes() {
      java.lang.Object ref = toMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProtoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, proto_);
      }
      if (!getToMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toMethod_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProtoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, proto_);
      }
      if (!getToMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toMethod_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zqgame.netty.io.proto.NettyIoProto.Head)) {
        return super.equals(obj);
      }
      com.zqgame.netty.io.proto.NettyIoProto.Head other = (com.zqgame.netty.io.proto.NettyIoProto.Head) obj;

      boolean result = true;
      result = result && getProto()
          .equals(other.getProto());
      result = result && getToMethod()
          .equals(other.getToMethod());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROTO_FIELD_NUMBER;
      hash = (53 * hash) + getProto().hashCode();
      hash = (37 * hash) + TOMETHOD_FIELD_NUMBER;
      hash = (53 * hash) + getToMethod().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Head parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zqgame.netty.io.proto.NettyIoProto.Head prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *报文头部
     * </pre>
     *
     * Protobuf type {@code com.zqgame.netty.io.proto.NettyIoProto.Head}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zqgame.netty.io.proto.NettyIoProto.Head)
        com.zqgame.netty.io.proto.NettyIoProto.HeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Head_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Head_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zqgame.netty.io.proto.NettyIoProto.Head.class, com.zqgame.netty.io.proto.NettyIoProto.Head.Builder.class);
      }

      // Construct using com.zqgame.netty.io.proto.NettyIoProto.Head.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        proto_ = "";

        toMethod_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Head_descriptor;
      }

      public com.zqgame.netty.io.proto.NettyIoProto.Head getDefaultInstanceForType() {
        return com.zqgame.netty.io.proto.NettyIoProto.Head.getDefaultInstance();
      }

      public com.zqgame.netty.io.proto.NettyIoProto.Head build() {
        com.zqgame.netty.io.proto.NettyIoProto.Head result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zqgame.netty.io.proto.NettyIoProto.Head buildPartial() {
        com.zqgame.netty.io.proto.NettyIoProto.Head result = new com.zqgame.netty.io.proto.NettyIoProto.Head(this);
        result.proto_ = proto_;
        result.toMethod_ = toMethod_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zqgame.netty.io.proto.NettyIoProto.Head) {
          return mergeFrom((com.zqgame.netty.io.proto.NettyIoProto.Head)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zqgame.netty.io.proto.NettyIoProto.Head other) {
        if (other == com.zqgame.netty.io.proto.NettyIoProto.Head.getDefaultInstance()) return this;
        if (!other.getProto().isEmpty()) {
          proto_ = other.proto_;
          onChanged();
        }
        if (!other.getToMethod().isEmpty()) {
          toMethod_ = other.toMethod_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zqgame.netty.io.proto.NettyIoProto.Head parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zqgame.netty.io.proto.NettyIoProto.Head) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object proto_ = "";
      /**
       * <pre>
       *协议名
       * </pre>
       *
       * <code>string proto = 1;</code>
       */
      public java.lang.String getProto() {
        java.lang.Object ref = proto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          proto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *协议名
       * </pre>
       *
       * <code>string proto = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProtoBytes() {
        java.lang.Object ref = proto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *协议名
       * </pre>
       *
       * <code>string proto = 1;</code>
       */
      public Builder setProto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        proto_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议名
       * </pre>
       *
       * <code>string proto = 1;</code>
       */
      public Builder clearProto() {
        
        proto_ = getDefaultInstance().getProto();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议名
       * </pre>
       *
       * <code>string proto = 1;</code>
       */
      public Builder setProtoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        proto_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toMethod_ = "";
      /**
       * <pre>
       *执行的方法
       * </pre>
       *
       * <code>string toMethod = 2;</code>
       */
      public java.lang.String getToMethod() {
        java.lang.Object ref = toMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toMethod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *执行的方法
       * </pre>
       *
       * <code>string toMethod = 2;</code>
       */
      public com.google.protobuf.ByteString
          getToMethodBytes() {
        java.lang.Object ref = toMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *执行的方法
       * </pre>
       *
       * <code>string toMethod = 2;</code>
       */
      public Builder setToMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *执行的方法
       * </pre>
       *
       * <code>string toMethod = 2;</code>
       */
      public Builder clearToMethod() {
        
        toMethod_ = getDefaultInstance().getToMethod();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *执行的方法
       * </pre>
       *
       * <code>string toMethod = 2;</code>
       */
      public Builder setToMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toMethod_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zqgame.netty.io.proto.NettyIoProto.Head)
    }

    // @@protoc_insertion_point(class_scope:com.zqgame.netty.io.proto.NettyIoProto.Head)
    private static final com.zqgame.netty.io.proto.NettyIoProto.Head DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zqgame.netty.io.proto.NettyIoProto.Head();
    }

    public static com.zqgame.netty.io.proto.NettyIoProto.Head getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Head>
        PARSER = new com.google.protobuf.AbstractParser<Head>() {
      public Head parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Head(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Head> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Head> getParserForType() {
      return PARSER;
    }

    public com.zqgame.netty.io.proto.NettyIoProto.Head getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zqgame.netty.io.proto.NettyIoProto.Base)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
     */
    com.zqgame.netty.io.proto.NettyIoProto.Head getHeader();
    /**
     * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
     */
    com.zqgame.netty.io.proto.NettyIoProto.HeadOrBuilder getHeaderOrBuilder();

    /**
     * <code>bytes body = 2;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code com.zqgame.netty.io.proto.NettyIoProto.Base}
   */
  public  static final class Base extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zqgame.netty.io.proto.NettyIoProto.Base)
      BaseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Base.newBuilder() to construct.
    private Base(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Base() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Base(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.zqgame.netty.io.proto.NettyIoProto.Head.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.zqgame.netty.io.proto.NettyIoProto.Head.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Base_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Base_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zqgame.netty.io.proto.NettyIoProto.Base.class, com.zqgame.netty.io.proto.NettyIoProto.Base.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.zqgame.netty.io.proto.NettyIoProto.Head header_;
    /**
     * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
     */
    public com.zqgame.netty.io.proto.NettyIoProto.Head getHeader() {
      return header_ == null ? com.zqgame.netty.io.proto.NettyIoProto.Head.getDefaultInstance() : header_;
    }
    /**
     * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
     */
    public com.zqgame.netty.io.proto.NettyIoProto.HeadOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 2;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!body_.isEmpty()) {
        output.writeBytes(2, body_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zqgame.netty.io.proto.NettyIoProto.Base)) {
        return super.equals(obj);
      }
      com.zqgame.netty.io.proto.NettyIoProto.Base other = (com.zqgame.netty.io.proto.NettyIoProto.Base) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && getBody()
          .equals(other.getBody());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Base parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zqgame.netty.io.proto.NettyIoProto.Base prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zqgame.netty.io.proto.NettyIoProto.Base}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zqgame.netty.io.proto.NettyIoProto.Base)
        com.zqgame.netty.io.proto.NettyIoProto.BaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Base_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Base_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zqgame.netty.io.proto.NettyIoProto.Base.class, com.zqgame.netty.io.proto.NettyIoProto.Base.Builder.class);
      }

      // Construct using com.zqgame.netty.io.proto.NettyIoProto.Base.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Base_descriptor;
      }

      public com.zqgame.netty.io.proto.NettyIoProto.Base getDefaultInstanceForType() {
        return com.zqgame.netty.io.proto.NettyIoProto.Base.getDefaultInstance();
      }

      public com.zqgame.netty.io.proto.NettyIoProto.Base build() {
        com.zqgame.netty.io.proto.NettyIoProto.Base result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zqgame.netty.io.proto.NettyIoProto.Base buildPartial() {
        com.zqgame.netty.io.proto.NettyIoProto.Base result = new com.zqgame.netty.io.proto.NettyIoProto.Base(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.body_ = body_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zqgame.netty.io.proto.NettyIoProto.Base) {
          return mergeFrom((com.zqgame.netty.io.proto.NettyIoProto.Base)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zqgame.netty.io.proto.NettyIoProto.Base other) {
        if (other == com.zqgame.netty.io.proto.NettyIoProto.Base.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zqgame.netty.io.proto.NettyIoProto.Base parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zqgame.netty.io.proto.NettyIoProto.Base) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.zqgame.netty.io.proto.NettyIoProto.Head header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zqgame.netty.io.proto.NettyIoProto.Head, com.zqgame.netty.io.proto.NettyIoProto.Head.Builder, com.zqgame.netty.io.proto.NettyIoProto.HeadOrBuilder> headerBuilder_;
      /**
       * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
       */
      public com.zqgame.netty.io.proto.NettyIoProto.Head getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.zqgame.netty.io.proto.NettyIoProto.Head.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
       */
      public Builder setHeader(com.zqgame.netty.io.proto.NettyIoProto.Head value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
       */
      public Builder setHeader(
          com.zqgame.netty.io.proto.NettyIoProto.Head.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
       */
      public Builder mergeHeader(com.zqgame.netty.io.proto.NettyIoProto.Head value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.zqgame.netty.io.proto.NettyIoProto.Head.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
       */
      public com.zqgame.netty.io.proto.NettyIoProto.Head.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
       */
      public com.zqgame.netty.io.proto.NettyIoProto.HeadOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.zqgame.netty.io.proto.NettyIoProto.Head.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.com.zqgame.netty.io.proto.NettyIoProto.Head header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zqgame.netty.io.proto.NettyIoProto.Head, com.zqgame.netty.io.proto.NettyIoProto.Head.Builder, com.zqgame.netty.io.proto.NettyIoProto.HeadOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zqgame.netty.io.proto.NettyIoProto.Head, com.zqgame.netty.io.proto.NettyIoProto.Head.Builder, com.zqgame.netty.io.proto.NettyIoProto.HeadOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 2;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 2;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zqgame.netty.io.proto.NettyIoProto.Base)
    }

    // @@protoc_insertion_point(class_scope:com.zqgame.netty.io.proto.NettyIoProto.Base)
    private static final com.zqgame.netty.io.proto.NettyIoProto.Base DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zqgame.netty.io.proto.NettyIoProto.Base();
    }

    public static com.zqgame.netty.io.proto.NettyIoProto.Base getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Base>
        PARSER = new com.google.protobuf.AbstractParser<Base>() {
      public Base parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Base(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Base> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Base> getParserForType() {
      return PARSER;
    }

    public com.zqgame.netty.io.proto.NettyIoProto.Base getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zqgame.netty.io.proto.NettyIoProto.Test)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string value = 1;</code>
     */
    java.util.List<java.lang.String>
        getValueList();
    /**
     * <code>repeated string value = 1;</code>
     */
    int getValueCount();
    /**
     * <code>repeated string value = 1;</code>
     */
    java.lang.String getValue(int index);
    /**
     * <code>repeated string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes(int index);
  }
  /**
   * Protobuf type {@code com.zqgame.netty.io.proto.NettyIoProto.Test}
   */
  public  static final class Test extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zqgame.netty.io.proto.NettyIoProto.Test)
      TestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Test.newBuilder() to construct.
    private Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test() {
      value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Test(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                value_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              value_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = value_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Test_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zqgame.netty.io.proto.NettyIoProto.Test.class, com.zqgame.netty.io.proto.NettyIoProto.Test.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList value_;
    /**
     * <code>repeated string value = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getValueList() {
      return value_;
    }
    /**
     * <code>repeated string value = 1;</code>
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated string value = 1;</code>
     */
    public java.lang.String getValue(int index) {
      return value_.get(index);
    }
    /**
     * <code>repeated string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes(int index) {
      return value_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < value_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < value_.size(); i++) {
          dataSize += computeStringSizeNoTag(value_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getValueList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zqgame.netty.io.proto.NettyIoProto.Test)) {
        return super.equals(obj);
      }
      com.zqgame.netty.io.proto.NettyIoProto.Test other = (com.zqgame.netty.io.proto.NettyIoProto.Test) obj;

      boolean result = true;
      result = result && getValueList()
          .equals(other.getValueList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValueCount() > 0) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValueList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zqgame.netty.io.proto.NettyIoProto.Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zqgame.netty.io.proto.NettyIoProto.Test prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zqgame.netty.io.proto.NettyIoProto.Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zqgame.netty.io.proto.NettyIoProto.Test)
        com.zqgame.netty.io.proto.NettyIoProto.TestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Test_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zqgame.netty.io.proto.NettyIoProto.Test.class, com.zqgame.netty.io.proto.NettyIoProto.Test.Builder.class);
      }

      // Construct using com.zqgame.netty.io.proto.NettyIoProto.Test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zqgame.netty.io.proto.NettyIoProto.internal_static_com_zqgame_netty_io_proto_NettyIoProto_Test_descriptor;
      }

      public com.zqgame.netty.io.proto.NettyIoProto.Test getDefaultInstanceForType() {
        return com.zqgame.netty.io.proto.NettyIoProto.Test.getDefaultInstance();
      }

      public com.zqgame.netty.io.proto.NettyIoProto.Test build() {
        com.zqgame.netty.io.proto.NettyIoProto.Test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zqgame.netty.io.proto.NettyIoProto.Test buildPartial() {
        com.zqgame.netty.io.proto.NettyIoProto.Test result = new com.zqgame.netty.io.proto.NettyIoProto.Test(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = value_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zqgame.netty.io.proto.NettyIoProto.Test) {
          return mergeFrom((com.zqgame.netty.io.proto.NettyIoProto.Test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zqgame.netty.io.proto.NettyIoProto.Test other) {
        if (other == com.zqgame.netty.io.proto.NettyIoProto.Test.getDefaultInstance()) return this;
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zqgame.netty.io.proto.NettyIoProto.Test parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zqgame.netty.io.proto.NettyIoProto.Test) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = new com.google.protobuf.LazyStringArrayList(value_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValueList() {
        return value_.getUnmodifiableView();
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public java.lang.String getValue(int index) {
        return value_.get(index);
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes(int index) {
        return value_.getByteString(index);
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public Builder setValue(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public Builder addValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public Builder addAllValue(
          java.lang.Iterable<java.lang.String> values) {
        ensureValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, value_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public Builder clearValue() {
        value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public Builder addValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zqgame.netty.io.proto.NettyIoProto.Test)
    }

    // @@protoc_insertion_point(class_scope:com.zqgame.netty.io.proto.NettyIoProto.Test)
    private static final com.zqgame.netty.io.proto.NettyIoProto.Test DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zqgame.netty.io.proto.NettyIoProto.Test();
    }

    public static com.zqgame.netty.io.proto.NettyIoProto.Test getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test>
        PARSER = new com.google.protobuf.AbstractParser<Test>() {
      public Test parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test> getParserForType() {
      return PARSER;
    }

    public com.zqgame.netty.io.proto.NettyIoProto.Test getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zqgame_netty_io_proto_NettyIoProto_Head_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zqgame_netty_io_proto_NettyIoProto_Head_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zqgame_netty_io_proto_NettyIoProto_Base_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zqgame_netty_io_proto_NettyIoProto_Base_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zqgame_netty_io_proto_NettyIoProto_Test_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zqgame_netty_io_proto_NettyIoProto_Test_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024netty_io_proto.proto\022&com.zqgame.netty" +
      ".io.proto.NettyIoProto\"\'\n\004Head\022\r\n\005proto\030" +
      "\001 \001(\t\022\020\n\010toMethod\030\002 \001(\t\"R\n\004Base\022<\n\006heade" +
      "r\030\001 \001(\0132,.com.zqgame.netty.io.proto.Nett" +
      "yIoProto.Head\022\014\n\004body\030\002 \001(\014\"\025\n\004Test\022\r\n\005v" +
      "alue\030\001 \003(\tB)\n\031com.zqgame.netty.io.protoB" +
      "\014NettyIoProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zqgame_netty_io_proto_NettyIoProto_Head_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zqgame_netty_io_proto_NettyIoProto_Head_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zqgame_netty_io_proto_NettyIoProto_Head_descriptor,
        new java.lang.String[] { "Proto", "ToMethod", });
    internal_static_com_zqgame_netty_io_proto_NettyIoProto_Base_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zqgame_netty_io_proto_NettyIoProto_Base_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zqgame_netty_io_proto_NettyIoProto_Base_descriptor,
        new java.lang.String[] { "Header", "Body", });
    internal_static_com_zqgame_netty_io_proto_NettyIoProto_Test_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_zqgame_netty_io_proto_NettyIoProto_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zqgame_netty_io_proto_NettyIoProto_Test_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
